# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-04 23:59
from __future__ import unicode_literals

import administrador.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingrediente',
            fields=[
                ('nombre', models.CharField(max_length=30, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('nombre', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('actual', administrador.fields.OneTrueBooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Plato',
            fields=[
                ('nombre', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('descripcion', models.TextField(max_length=30)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ingredientes', models.ManyToManyField(to='administrador.Ingrediente')),
            ],
        ),
        migrations.AddField(
            model_name='menu',
            name='platos',
            field=models.ManyToManyField(to='administrador.Plato'),
        ),
    ]
