# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-09 16:04
from __future__ import unicode_literals

import administrador.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ingrediente',
            fields=[
                ('nombre', models.CharField(max_length=30, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('nombre', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('actual', administrador.fields.OneTrueBooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Plato',
            fields=[
                ('nombre', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('descripcion', models.TextField(max_length=30)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ingredientes', models.ManyToManyField(to='administrador.Ingrediente')),
            ],
        ),
        migrations.AddField(
            model_name='menu',
            name='platos',
            field=models.ManyToManyField(to='administrador.Plato'),
        ),
    ]
