# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-10 00:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cuentas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BilleteraElectronica',
            fields=[
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='cuentas.Proveedor')),
                ('pin', models.CharField(max_length=6)),
            ],
        ),
    ]
