# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-25 22:53
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0007_alter_validators_add_error_messages'),
    ]

    operations = [
        migrations.CreateModel(
            name='Billetera',
            fields=[
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('pin', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('ci', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('fecha_nacimiento', models.DateField(verbose_name='fecha de nacimiento')),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1)),
                ('telefono', models.CharField(max_length=12, validators=[django.core.validators.RegexValidator(code='telefono_invalido', message='El teléfono debe tener este formato: 0212-1234567', regex='^[0-9]{4}-[0-9]{7}$')])),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Historial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.FloatField()),
                ('fecha', models.DateTimeField()),
                ('historial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trans', to='cliente.Historial')),
            ],
        ),
        migrations.AddField(
            model_name='billetera',
            name='creditos',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='creditos', to='cliente.Historial'),
        ),
        migrations.AddField(
            model_name='billetera',
            name='debitos',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='debitos', to='cliente.Historial'),
        ),
    ]
