# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-10 00:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0001_initial'),
        ('cuentas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredientes', models.ManyToManyField(to='administrador.Ingrediente')),
            ],
        ),
        migrations.RemoveField(
            model_name='proveedor',
            name='inventario',
        ),
        migrations.AddField(
            model_name='inventario',
            name='rif_proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cuentas.Proveedor'),
        ),
    ]
