# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-27 17:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proveedor', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventario',
            old_name='rif_proveedor',
            new_name='usuario',
        ),
    ]
