# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-23 23:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='email',
            field=models.EmailField(default='default@mail.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cliente',
            name='sexo',
            field=models.CharField(choices=[(b'M', b'Masculino'), (b'F', b'Femenino')], max_length=1),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(max_length=12),
        ),
    ]
