# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-24 00:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0002_auto_20160523_2357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='clave',
            field=models.CharField(max_length=30),
        ),
    ]
