# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-26 16:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0004_auto_20160526_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='fecha_nacimiento',
            field=models.DateField(verbose_name=b'fecha de nacimiento'),
        ),
    ]
