# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-26 19:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0006_auto_20160526_1747'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='fecha_nacimiento',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='sexo',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='telefono',
        ),
    ]
