# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-26 19:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('registro', '0006_auto_20160526_1747'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('rif', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('telefono', models.CharField(max_length=12)),
                ('direccion', models.CharField(max_length=128)),
                ('usuario', models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
