# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-26 19:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0007_auto_20160526_1912'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='ci',
        ),
        migrations.AddField(
            model_name='cliente',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
