# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-26 19:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0008_auto_20160526_1913'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='usuario',
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
    ]
