# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-26 19:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('registro', '0009_auto_20160526_1917'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('ci', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('fecha_nacimiento', models.DateField(verbose_name='fecha de nacimiento')),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1)),
                ('telefono', models.CharField(max_length=12)),
                ('usuario', models.OneToOneField(default='1', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
