# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-27 03:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0009_auto_20160526_2031'),
        ('registro', '0013_cliente_usuario'),
    ]

    operations = [
    ]
