# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-04 19:56
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0017_auto_20160604_0100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(max_length=12, validators=[django.core.validators.RegexValidator(code='telefono_invalido', message='El teléfono debe tener este formato: 0212-1234567', regex='^[0-9]{4}-[0-9]{7}$')]),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='telefono',
            field=models.CharField(max_length=12, validators=[django.core.validators.RegexValidator(code='telefono_invalido', message='El teléfono debe tener este formato: 0212-1234567', regex='^[0-9]{4}-[0-9]{7}$')]),
        ),
    ]
